### ISSUE TITLE
Only 600+ files matched on Archive.org TOSEC package?

### ISSUE THREAD

**Issue by mgtroyas** [ladyeklipse/ZX-Pokemaster#10]
Hi, first of all thank you very much for this tool, is really helpful.

I'm surely doing something wrong, but I downloaded your 2017 TOSEC package from Archive.org, pointed ZX Pokemaster to the "Games" foder, and applied some basic rules. Only 600+ games are being copied to the output folder. I've tried different settings but always get the same result. They are on different formats and for several Spectrum hardware models.

The other files are ok, as I've played several ones on FUSE. Any tip about what could be wrong?

[settings.zip](https://github.com/ladyeklipse/ZX-Pokemaster/files/6564648/settings.zip)

**Comment by ladyeklipse** [comment]
1. Your collection is obsolete, use this one:

https://archive.org/details/zx-spectrum-tosec-set-v-2020-02-18-lady-eklipse

2. I didn’t test it yet, but it may have something to do with you copying files to and from a remote machine on a local network. Some operations might have been blocked by a firewall.

**Comment by mgtroyas** [comment]
Thank you very much. I copied the files to a local drive and it worked, but at the end the problem wasn't being using a network drive, but the path length: I moved the files to a folder on the root of the network drive and also all of them were classified. Probably only the shorter filenames were processed on the original location. Perhaps you could catch those errors to warn the user it's ignoring some files.

I've also downloaded the 2020 archive, and I'm organizing it right now. Thanks!
