### ISSUE TITLE
Some sites I found with unknown files & a couple of bugs

### ISSUE THREAD

**Issue by ghost** [ladyeklipse/ZX-Pokemaster#6]
This program is awesome ! I can't believe i've only just found it. Anyway, I got some files from the following sites that the Pokemaster doesn't detect so are also not in TOSEC. I'm not sure when the next TOSEC update is so I hope it's not bad timing. (I used Pokemaster v1.3 beta 1).

http://speccy-live.untergrund.net/tag/cracks/
(Rubber Desert vol 1 + 2)

http://retrospec.sgn.net/users/tomcat/yu/TRDosReCracks.php

The next link is an older version of the site that contains a lot of the 'Denied' ReCracks.

http://retrospec.sgn.net/users/tomcat/TRD/TRDosReCracks.html

With the ReCracks some were named wrong by Pokemaster like 'Muncher Crack Intro (1996-01)(flash)'. It's the full game  with trainer.

I also found a site a few years ago (i'll have to look it up) that contained a lot of the 'Denied' games in TZX format. It included all the Codemasters Quattro Compilations ( a lot are not in TOSEC and Pokemaster only detected 2) and another Ultimate Play The Game compilation.

I hope this all can be used to add to ZX Pokemaster. Thanks for the amazing work on this.

**Comment by eklipse2009** [comment]
Thank you for your comments!
The deadline for the next TOSEC release comes very soon, so I'm afraid there is no time to add the files from sites you mentioned. Besides, I already have a list of 17 sites which might contain files that are still not added to TOSEC.
I'll do my best to add as many files as possible from the sites you mentioned, but please expect this to happen no sooner than the summer release of TOSEC.

**Comment by ZappaUtopia** [comment]
I wasn't expecting you to add them as soon as possible, I just thought i'd let you know. :)

**Comment by zzedmore** [comment]
I noticed that a lot of the games in the 2 sites of the first post (retrospec) are not detected by Pokemaster (or TOSEC). In particular, there are some fantastic All-in-One Z80 files of Multi-Load games that load all at once ! Very handy.
