### ISSUE TITLE
alltipshoppokes discontinued ?

### ISSUE THREAD

**Issue by ghost** [ladyeklipse/ZX-Pokemaster#7]
Hi, just wondering if your 'alltipshoppokes' github will be updated or have you discontinued it ? Would love to see an update.

I don't why the http://www.the-tipshop.co.uk/ doesn't include the actual .POK files instead of just typing each cheat as text.

**Comment by eklipse2009** [comment]
It wll be updated when I resume work on ZX Pokemaster. It is NOT discontinued, just other things got into priority.

**Comment by ladyeklipse** [comment]
AllTipshopPokes is NOT discontinued and was last updated on February, 18, 2021. More updates will follow, but with irregular frequency.
