### ISSUE TITLE
[Request] Option to convert POK to Retroarch CHT format

### ISSUE THREAD

**Issue by zzedmore** [ladyeklipse/ZX-Pokemaster#9]
I recently discovered this program and I must say it's a godsend ! Thanks for this, there's one thing that could put the cherry on top and that's an option to convert the POK files to Retroarch CHT format. I ask this because there are thousands on Retroarch and i'd just like to be able to have the cheats for the games I have in the chosen naming scheme (using your program). This https://github.com/RobLoach/libretro-database-cht-spectrum is the Github that converts them but like I say, there are thousands of them and a lot of them use the alternate name for the games so sometimes difficult to find the required cheat.

This would be great if you could add this feature! Thanks for your hard work.

**Comment by ladyeklipse** [comment]
Yes, I can easily add an option to generate CHT files, those are very straightforward.
Do I understand correclty that RetroArch expects them to be in the same folder and have the same base name as the game file loaded?

**Comment by zzedmore** [comment]
I think with Retroarch they go in a 'cheats' folder and Spectrum subfolder, you have to manually load them so the cheat filename doesn't have to match the game name.

So just a straight forward convert from POK to CHT is good enough (or option to directly output CHT instead).

**Comment by zzedmore** [comment]
Hi, may I ask when the next version is due ?

**Comment by ladyeklipse** [comment]
There is no due date. When I have time and mood for it.

**Comment by zzedmore** [comment]
Just a note, when you add this could you have it as a converter so you would specify the folder with POK files and then choose an output directory for the CHT files ? This is because there are some files that Pokemaster doesn't recognize (like https://github.com/ladyeklipse/ZX-Pokemaster/issues/9) so no POK will be output. There are also some new games and custom ones that aren't recognized.

**Comment by zzedmore** [comment]
Hi, sorry to bother you. Is there any chance of this (just a straight POK to CHT converter).

**Comment by zzedmore** [comment]
In the meantime, do you have a simple script that could convert them ? (without needing to implement it into Pokemaster). You said above that 

> I can easily add an option to generate CHT files, those are very straightforward.

If not then i'll move on. :)

**Comment by ladyeklipse** [comment]
No, and I'm not working on the project at the moment.

**Comment by zzedmore** [comment]
Whoah! Sorry I spoke.

**Comment by zzedmore** [comment]
You need some serious anger management.
